# This is what you must enter as login to create a new account
loginNewUser: new

# Number of days before a mail expires and is deleted from the mailbox, unless it is pinned
mailMaxExpirationDays: 30

# Number of messages a user can pin to prevent auto deletion
mailMaxPinnedMessages: 20

# Maximum character count in a messages
mailMaxMessageLength: 1024

# Maximum character count in a message topics
mailMaxTopicLength: 40

